# Generated by Django 3.0.5 on 2020-05-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_laptops'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='EMAIL',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='NAME',
            new_name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
