# Generated by Django 3.0.5 on 2020-05-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200517_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='EMAIL',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='NAME',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
