# Generated by Django 3.0.5 on 2020-05-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200517_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='EMAIL',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='NAME',
            new_name='name',
        ),
    ]
