# Generated by Django 3.0.5 on 2020-05-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200517_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
