# Generated by Django 3.0.5 on 2020-05-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200515_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
