# Generated by Django 3.0.5 on 2020-05-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200517_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='price_per_item',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
