# Generated by Django 3.0.5 on 2020-05-17 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200517_0918'),
        ('orders', '0011_auto_20200517_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Status'),
        ),
    ]
