# Generated by Django 3.0.5 on 2020-05-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200517_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('RES', 'Корзина'), ('NEW', 'Новый заказ'), ('CANC', 'Отменённый заказ'), ('CLOS', 'Закрытый заказ')], default='RES', max_length=20),
        ),
    ]
