# Generated by Django 3.0.5 on 2020-06-05 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20200604_2245'),
        ('orders', '0020_productinbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_pi', to='myapp.Customer'),
        ),
    ]
