# Generated by Django 3.0.5 on 2020-06-05 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200605_1440'),
        ('myapp', '0013_auto_20200604_2245'),
        ('orders', '0021_productinorder_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='nmb',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='session_key',
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_productinbasket', to='myapp.Customer'),
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='price_per_item',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productinbasket', to='products.Product'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_basket', to='myapp.Customer')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='basket',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='orders.Basket'),
        ),
    ]
