# Generated by Django 3.0.5 on 2020-06-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200605_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['-created'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('RES', 'В обработке'), ('NEW', 'Новый заказ'), ('CANC', 'Отменённый заказ'), ('CLOS', 'Закрытый заказ')], default='RES', max_length=20),
        ),
    ]
