# Generated by Django 3.0.5 on 2020-05-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200515_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=None, upload_to='products_images/'),
        ),
    ]
