# Generated by Django 3.0.5 on 2020-05-16 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('os', models.CharField(default=None, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cpu', models.CharField(default=None, max_length=15, null=True)),
                ('cores', models.IntegerField(default=0)),
                ('memory_freq', models.CharField(default=None, max_length=10, null=True)),
                ('RAM', models.CharField(default=None, max_length=10, null=True)),
                ('resolution', models.CharField(default=None, max_length=40, null=True)),
                ('display_diagonal', models.CharField(default=None, max_length=30, null=True)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ProductPhone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('is_active', models.BooleanField(default=True)),
                ('screen', models.CharField(default=None, max_length=15, null=True)),
                ('dimensions', models.CharField(default=None, max_length=15, null=True)),
                ('os', models.CharField(default=None, max_length=15, null=True)),
                ('ROM', models.CharField(default=None, max_length=10, null=True)),
                ('bluetooth', models.IntegerField(default=0)),
            ],
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
