# Generated by Django 3.0.5 on 2020-05-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200515_2240'),
        ('products', '0007_auto_20200516_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='laptop',
            new_name='ProductLaptop',
        ),
    ]
