# Generated by Django 3.0.5 on 2020-05-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200517_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.SlugField(blank=True, default=None, max_length=130, null=True, unique=True),
        ),
    ]
