# Generated by Django 3.0.5 on 2020-05-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фотография продукта', 'verbose_name_plural': 'Фотографии продуктов'},
        ),
    ]
