# Generated by Django 3.0.5 on 2020-05-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200526_1156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingStar',
            new_name='ReviewsStar',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
