# Generated by Django 3.0.5 on 2020-05-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200526_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('L', 'Laptop'), ('Ph', 'Phone')], default=None, max_length=3, null=True),
        ),
    ]
