# Generated by Django 3.0.5 on 2020-05-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Laptops', 'Laptop'), ('Phones', 'Phone')], default=None, max_length=10, null=True),
        ),
    ]
