# Generated by Django 3.0.5 on 2020-05-30 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200529_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlaptop',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_laptop', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productphone',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_phone', to='products.Product'),
        ),
    ]
